### PR TITLE
Fix omp_num_teams_generic, honor explicit num_teams before loop_tripc…

### PR DESCRIPTION
**Pull request by ronlieb**

### CODE REVIEW

**Comment by JonChesterfield** [comment]
LG. Is there a reasonable way of testing this?

**Comment by ronlieb** [comment]
it passes our smoke  tests which includes the test case aomp_num_teams_generic which revealed the issue. Is that reasonable ?

**Comment by JonChesterfield** [comment]
Yep, that's persuasive. Thanks

**Comment by ronlieb** [comment]
thanks for the review, pushin it now ...

**Pull request merged**
