### PR TITLE
Add offloading-related flags to flang

### PR DESCRIPTION
**Pull request by skatrak**
New flags added by the driver, accepted by flang-new and stored for later use, ported from clang:
  - `-fopenmp-targets`
  - `-fvisibility`
  - `-include`
  - `-disable-llvm-passes`
  - `-mlink-builtin-bitcode`
  - `-internal-isystem`
  - `-fcuda-is-device`
  - `-fopenmp-is-device`
  - `-fopenmp-host-ir-file-path`
  - `-aux-triple`

In addition, processing of the `-disable-llvm-passes`, `-internal-isystem` and `-include` flags. The other flags are only stored in _Frontend/*Options_ classes, so they can be made available to wherever that information can be used to influence lowering passes or code generation.

Currently looking for feedback as to which of these flags are more useful at the moment, and whether there are any that will not be necessary. This is still a work in progress, currently looking at updating related unit tests and checking that no issues are introduced by these changes.

### CODE REVIEW

**Review by jsjodin — COMMENTED** [review]
Do all tests pass with these changes? I remember I had to fix a flang test for things to pass. Also if we are upstreaming these we will have to add tests for the new options, and probably split up more complicated ones into separate Phabricator reviews.

**Comment by skatrak** [comment]
Tests are not passing currently, I decided to create this PR while I started work on these. But it looks like it's probably not going to need much effort.

I was thinking of making each flag its own Phabricator review, but since what I've done here adds the flags but doesn't do anything with them for the most part, I was unsure if it would be better to wait instead of pushing something half-done. I'm open to suggestions, anyways. I was just thinking that adding unimplemented flags that promise to do something (on the output of `flang-new -help`) would be frowned upon.

**Comment by skatrak** [comment]
The unit test for the driver help is now updated, and I also added new tests for the flags that are not just stored but also implemented.

**Comment by skatrak** [comment]
Earlier today I created a Phabricator patch for one of the flags included in this PR: https://reviews.llvm.org/D143493.

According to the comments I got, it looks like we won't be able to upstream most of these new flags yet, as their current usefulness is entirely tied to completing a basic amount of offloading support. The reasoning is that there is currently no other reason for them to exist other than the expectation that they might later be used to implement device offload.

**Comment by skatrak** [comment]
Closing PR to be replaced by smaller PR's implementing each flag.

**Pull request closed without merging**
