### PR TITLE
TargetID Support in AOMP - Part 2

### PR DESCRIPTION
**Pull request by saiislam**
Left over Driver changes to support multi-arch compilation
using TargetID and --offload-arch option.

This PR is based on previous PRs --> #125 --> #124 --> #123.
They should be reviewed and merged in the same order.

### CODE REVIEW

**Comment by saiislam** [comment]
Direct link to correct review commit: https://github.com/ROCm-Developer-Tools/llvm-project/pull/126/commits/0ea95418e50b95ed96b0e33bb8f70ffe5011df7e

**Comment by gregrodgers** [comment]
How do we test with all the different branches?

**Comment by saiislam** [comment]
These branches are hierarchical.

- aomp-dev
  - target-id-0
     -  target-id-1
        - target-id-2
          - target-id-3 (this branch)
So, for overall testing one can take this branch (PR #126 ), rebase it with aomp-dev and test.

**Comment by saiislam** [comment]
Replaced by PR #135

**Pull request closed without merging**
