### PR TITLE
Add gfx90a to list of gpu archs

### PR DESCRIPTION
**Pull request by carlobertolli**

### CODE REVIEW

**Comment by gregrodgers** [comment]
When did we loose the x10 multiplier?    Using alphamerics such as 90a in _DEVICE_GPU makes it no longer an integer and useless as a generational macro.   I understand that AMD is not purely using this number as a generational connotation.   But not using an integer makes this macro almost as useless as the __gfxXXX__ macros .

This was what it looked like back in aomp11.

https://github.com/ROCm-Developer-Tools/amd-llvm-project/blob/aomp11/clang/lib/Headers/offload_macros.h

**Comment by gregrodgers** [comment]
I need to look for the upstream review of offload_macros.h.

**Comment by ronlieb** [comment]
the naming issue came up about a year ago when we were moving content to amd-stg-open.
it was pointed out at the time that our use of 10x would not hold for future arch names.
Gfx90a was cited as the initial example.

**Comment by gregrodgers** [comment]
The x10 multiplier was for things like amd90a and amd90c.   Here is the current state of the upstream review. 

https://reviews.llvm.org/D84743

**Review by gregrodgers — APPROVED** [review]

**Pull request merged**
