### PR TITLE
Implement RT call omp_target_is_accessible

### PR DESCRIPTION
**Pull request by carlobertolli**

### CODE REVIEW

**Review by ronlieb — APPROVED** [review]

**Comment by ronlieb** [comment]
[AMD Official Use Only - Internal Distribution Only]

I think Greg needs this in for Target-id to ship as part of AOMP 13.0-3 (this week?)
I think Greg is planning a merge of trunk after 13.0-3 ships

**Comment by JonChesterfield** [comment]
Can the patches be proposed to trunk at the same time then, and we update aomp to match as they land in trunk? Assuming trunk patches land slower and somewhat modified to the ones on aomp.

**Comment by carlobertolli** [comment]
@JonChesterfield good point about trunk-ization. I am in the process of building trunk locally so I can create a revision. Should be ready by later today. Thanks!

**Comment by carlobertolli** [comment]
I found an issue with this implementation. This is a counter-example that shows the difference between omp_target_is_present and omp_target_is_accessible:

```
int def_d = omp_get_default_device();
int *b = malloc(10*sizeof(int), def_d);
int *a = omp_target_alloc(10*sizeof(int), def_d);
#pragma omp target data map(b[:10])
{
  omp_target_is_present(a, def_d); // a is not mapped, return false
  omp_target_is_present(b, def_d); // b is mapped, return true
  
  // a is accessible on default device, return true
  omp_target_is_accessible(a, 10*sizeof(int), def_d); 
  
  // b is accessible on default device, return false
  omp_target_is_accessible(b, 10*sizeof(int), def_d;
}
```

This highlights that something that is not mapped is not necessarily unaccessible on a device, if it was allocated with a proper runtime call.
To implement this literally, we would need to keep track of (startPtr,startPtr+size) of all target_alloc invocations and check those as well (along with items mapped via map clauses).
Am I missing something?

**Review by gregrodgers — APPROVED** [review]

**Comment by gregrodgers** [comment]
This looks straightforward.  I will merge this now into 13.0-4 so we can add aomp testing, especially omp_is_present tests.

**Pull request merged**
