### PR TITLE
An issue was observed in the test_target_parallel.c sollve test that …

### PR DESCRIPTION
**Pull request by estewart08**
This change is not upstream so I wanted to get your thoughts on potential consequences.

### CODE REVIEW

**Comment by estewart08** [comment]
Yes, it allows the sollve test to pass. Smoke/OpenMPApps pass as well.

**Comment by JonChesterfield** [comment]
This change replaces `(GetNumberOfThreadsInBlock() - 1) & ~(WARPSIZE - 1);` with GetNumberOfThreadsInBlock(). What's the underlying problem in the test?

I'm wary because this is close to code using smid(), which I suspect to be inherently broken on amdgcn. Some discussion in aomp/issues/73

**Comment by estewart08** [comment]
The problem the test reveals is that we go against the spec with what omp_get_max_threads() returns.  Clang's interpretation of SPMD vs generic kernel combined with returning the number of workers will cause issues due to the master warp in generic mode being subtracted. The number of workers in team shows 192 and of course SPMD will have 256 workers.  If one calls 
```
#pragma omp target
int max_threads = omp_get_max_threads();
```
Then under the original interpretation one will see 192. Upon creation of a parallel target region following the above code
```
#pragma omp target parallel 
int num_threads = omp_get_num_threads();
```
Num_threads will show 256, which is greater than the above 192. This goes against the spec which states, "The omp_get_max_threads routine returns an upper bound on the number of threads that could be used to form a new team if a parallel construct without a num_threads clause were encountered after execution returns from this routine." Even though the generic kernel has 192 active threads the call to get MAX threads should return the higher thread count of the two kernel types.

**Comment by JonChesterfield** [comment]
That's convincing, thanks. Would you mind raising a patch against upstream as well? nvptx presumably shows the same misbehaviour.

**Pull request merged**
