### PR TITLE
Remove hip automatic mode

### PR DESCRIPTION
**Pull request by JonChesterfield**
Replace hip automatic mode, and the open_cuda headers, with a header supporting only the API used by deviceRTL.

Pull request to show both compiler and deviceRTL change together. I'm planning to land the deviceRTL subset first. The compiler change could be broken down further. I believe I've caught all the automatic mode code in clang but there may be some remaining.

The cuda_shim.ll works around functions being annotated as 'convergent' by default, whereas the cuda builtins it replaces were not. Tests still pass if the functions are aliased directly, with greater change to the CFG.

In addition to the tests, this was sanity checked by comparing the amdgcn deviceRTL bitcode against head. The majority of the code is unchanged. There are some inverted conditionals with associated basic block reordering due to the change from builtins to inlined wrappers. I think these are all due to phase ordering - intrinsics are replaced before the always inline pass.

One of the external functions that was previously analysed and had the convergent attribute removed, retains it after this change. I think that's acceptable.

### CODE REVIEW

**Comment by ronlieb** [comment]
Lgtm

**Comment by jsjodin** [comment]
LGTM

**Comment by JonChesterfield** [comment]
Thanks! I've landed the deviceRTL patch. I'll leave it a few days before dropping the compiler support for automatic mode.

**Comment by JonChesterfield** [comment]
I think the dust has settled from the deviceRTL change. Rebased, merging.

**Pull request merged**
