### PR TITLE
Add include path of AOMP/include for fortran offload to find mod files

### PR DESCRIPTION
**Pull request by ronlieb**
pull in patch from Shivarama to add include for target offload fortran compiles. allows mod files to be found

### CODE REVIEW

**Comment by JonChesterfield** [comment]
Patch looks good. Test?

**Comment by ronlieb** [comment]
test case added 
https://github.com/ROCm-Developer-Tools/aomp/pull/53

**Comment by richardbleikamp** [comment]
Looks ok to me.  
Question about SmallString<128>: is the "128" just the initial size, and the string will automatically graw as needed?

**Comment by ronlieb** [comment]
yes, the size is an initial one, and allowed to grow.

http://llvm.org/doxygen/classllvm_1_1SmallString.html

**Pull request merged**
